# Generated by Django 4.2.5 on 2023-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtsUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt', models.CharField(blank=True, max_length=200, null=True)),
                ('attuid', models.CharField(blank=True, max_length=10, null=True)),
                ('employeename', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('workname', models.CharField(blank=True, max_length=200, null=True)),
                ('worktype', models.CharField(blank=True, max_length=200, null=True)),
                ('emptype', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('pvdate', models.CharField(blank=True, max_length=30, null=True)),
                ('billedhrs', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ats_utilization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=13, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('attcapacity', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('idccapacity', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'att_calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdcProjectSystemTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=4000, null=True)),
                ('project', models.CharField(blank=True, max_length=4000, null=True)),
                ('system', models.CharField(blank=True, max_length=4000, null=True)),
                ('tools', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'idc_project_system_tools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdcReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcprojectname', models.CharField(blank=True, max_length=100, null=True)),
                ('pmt', models.CharField(blank=True, max_length=200, null=True)),
                ('workname', models.CharField(blank=True, max_length=200, null=True)),
                ('vicepresident', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('onshorecontact', models.CharField(blank=True, max_length=100, null=True)),
                ('idccontact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'idc_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdcUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt', models.CharField(blank=True, max_length=200, null=True)),
                ('attuid', models.CharField(blank=True, max_length=10, null=True)),
                ('employeename', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('workname', models.CharField(blank=True, max_length=200, null=True)),
                ('worktype', models.CharField(blank=True, max_length=200, null=True)),
                ('schedulestart', models.DateField(blank=True, null=True)),
                ('schedulefinish', models.DateField(blank=True, null=True)),
                ('entitytype', models.CharField(blank=True, max_length=200, null=True)),
                ('emptype', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('reqby', models.CharField(blank=True, max_length=200, null=True)),
                ('team', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('pvdate', models.CharField(blank=True, max_length=30, null=True)),
                ('billedhrs', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'idc_utilization',
                'managed': False,
            },
        ),
    ]
