# Generated by Django 4.2.5 on 2023-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCDeptVendorempV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('monthyy', models.CharField(blank=True, max_length=30, null=True)),
                ('employee', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contractor', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'IDC_dept_vendoremp_v',
                'managed': False,
            },
        ),
    ]
