# Generated by Django 4.2.5 on 2023-10-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_idcdeptvendorempv'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCVPHeadcountV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janheadcount', models.IntegerField()),
                ('febheadcount', models.IntegerField()),
                ('marheadcount', models.IntegerField()),
                ('aprheadcount', models.IntegerField()),
                ('mayheadcount', models.IntegerField()),
                ('junheadcount', models.IntegerField()),
                ('julheadcount', models.IntegerField()),
                ('augheadcount', models.IntegerField()),
                ('sepheadcount', models.IntegerField()),
                ('octheadcount', models.IntegerField()),
                ('novheadcount', models.IntegerField()),
                ('decheadcount', models.IntegerField()),
            ],
            options={
                'db_table': 'idc_vp_headcount_v',
                'managed': False,
            },
        ),
    ]
