# Generated by Django 4.2.5 on 2023-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_idcvpheadcountv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='IDCDeptVendorempV',
        ),
        migrations.DeleteModel(
            name='IDCVPHeadcountV',
        ),
    ]
