# Generated by Django 4.2.5 on 2023-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_myview_delete_idcdeptvendorempv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCVPHeadcountV',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('janheadcount', models.IntegerField()),
                ('febheadcount', models.IntegerField()),
                ('marheadcount', models.IntegerField()),
                ('aprheadcount', models.IntegerField()),
                ('mayheadcount', models.IntegerField()),
                ('junheadcount', models.IntegerField()),
                ('julheadcount', models.IntegerField()),
                ('augheadcount', models.IntegerField()),
                ('sepheadcount', models.IntegerField()),
                ('octheadcount', models.IntegerField()),
                ('novheadcount', models.IntegerField()),
                ('decheadcount', models.IntegerField()),
            ],
            options={
                'db_table': 'idc_vp_headcount_v',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MyView',
        ),
    ]
